
spring:
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 5000MB
      max-request-size: 5000MB
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/lz?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    driver-class-name:  com.mysql.jdbc.Driver
    username:  root
    password:  123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:/mapper/*.xml
server:
  port: 8090

pagehelper:
  helperDialect: mysql
  reasonable: true




  
  supportMethodsArguments: true
  params: count=countSql
